#!/bin/bash
# Programa copia3
if test $# -ne 2
then
echo Uso de copia: copia f1 f2
echo Observe que copia necesita dos argumentos
exit 1
else

if cp "$1" "$2" 2>/dev/null
then
echo " $1 ha sido copiado a $2"
exit 0
else
echo " $1 no ha sido copiado a $2 "
exit 1
fi
fi

