#!/bin/bash
# Programa copia3
if test $# -ne 2
then
echo Uso de copia: copia f1 f2
echo Observe que copia necesita dos argumentos
exit 1
else

file_name=$(echo $2|tr " " "_")
echo $var

if cp $1 file_name 2>/dev/null
then
echo " $1 ha sido copiado a $file_name "
exit 0
else
echo " $1 no ha sido copiado a $file_name "
exit 1
fi
fi

