#!/bin/bash
# Programa vermandatos3 (ejercicio 7).

for p in $(ls -d /proc/[1-9]*)
do
    content=$(cat $p/cmdline | tr "\0" " " )
    if [ -z "$content" ]
    then
        echo "$p: SIN MANDATO"
    else
        echo "$p:  $content"
    fi
    printf \\n
done

