#!/bin/bash
# Programa vermandatos2

for p in $(ls -d /proc/[1-9]*)
do
    content=$(cat $p/cmdline)
    if [ -z "$content" ]
    then
        echo "$p: SIN MANDATO"
    else
        echo "$p:  $content"
    fi
    printf \\n
done

